### ISSUE TITLE
Postman collection (api) contains duplicate in URL : /products/{{ID}}/{{product-id}}

### ISSUE THREAD

**Issue by anton-tsiatsko** [commercetools/commercetools-postman-collection#12]
Doc  : https://docs.commercetools.com/http-api-projects-products#update-product
Endpoint: /{projectKey}/products/{id}

Postman:
{{host}}/{{projectKey}}/products/{{ID}}/{{product-id}}

**Comment by jenschude** [comment]
Thanks for the report

I fixed the issue in our generator updated the collection and directly found another small issue. :)

Should work now as expected.
