### ISSUE TITLE
Misleading variable name in <get ByProjectKeyProductSelectionsKeyByKeyProducts>

### ISSUE THREAD

**Issue by sfernengel** [commercetools/commercetools-postman-collection#15]
In the new postman collection get query to fetch products that are assigned to a product selection contains wrong variable name.
**Original:**
{{host}}/{{project-key}}/product-selections/key={{**product-key**}}/products

**Correct version should be:**
{{host}}/{{project-key}}/product-selections/key={{**product-selection-key**}}/products

Also shouldn't the name be get ByProjectKeyProductSelectionsByKeyProducts?

**Comment by jenschude** [comment]
Should be fixed with bc26f72

Thanks for the report!

**Comment by jenschude** [comment]
The generator tries to generate a unique name from the URI and in case there was no method annotation it will include the path fragment "key" in the name
