### ISSUE TITLE
Misleading variable name in <get ByProjectKeyProductSelectionsByIDProducts>

### ISSUE THREAD

**Issue by sfernengel** [commercetools/commercetools-postman-collection#16]
In the new postman collection get query to fetch products that are assigned to a product selection contains wrong variable name.
**Original:**
{{host}}/{{project-key}}/product-selections/{{**product-id**}}/products

**Correct version should be:**
{{host}}/{{project-key}}/product-selections/{{**product-selection-id**}}/products

**Comment by jenschude** [comment]
Should be fixed with bc26f721349135b1e5aae4841262e632e190751d

Thanks for the report!
