### ISSUE TITLE
Collection import fails on Bruno

### ISSUE THREAD

**Issue by davidweterings** [commercetools/commercetools-postman-collection#24]
I use https://www.usebruno.com/ instead of Postman. When importing the collection it fails because the request.method is sometimes lowercase (I've seen 'get', 'delete', 'head')

According to https://datatracker.ietf.org/doc/html/rfc9110#section-9 it should always be uppercase, so could this be fixed in this collection?

**Comment by jenschude** [comment]
Hey David

Why not directly using our Bruno collection? ;)

https://docs.commercetools.com/sdk/bruno

**Comment by davidweterings** [comment]
Oops, I missed that one, thank you!
