### ISSUE TITLE
Authorization samples include a leading https://

### ISSUE THREAD

**Issue by briantomkins** [commercetools/commercetools-postman-collection#9]
A small issue with the authorization examples as they all lead with https://{{auth_url}}.....
The auth_url variable already contains a leading "https://" when downloaded from the Management Console / Developer / Create API client.

Users get the error : 
"There was an error connecting to https://https://auth.sphere.io..."

Removing the https:// from the postman examples avoids this error.

**Comment by jenschude** [comment]
Solved with a239b73
